[package]
authors = [""]
edition = "2018"
name = "fast-prototype"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = {version = "0.3", features = ["canvas"]}
